# Simple golang server with a gio web app

# https://fly.io/blog/hugo-s-there-flying-with-hugo-and-caddy/

# use caddy so we can run a Webserver to server it.
# can embed the WASM filesinside 

MAKE_FSPATH=./../../../_make
include $(MAKE_FSPATH)/_inc.mk

this-print:
	$(MAKE) inc-print


this-dep-os:
	$(MAKE) inc-dep-os



GO_EX=$(PWD)

GIO_EX_PATH=$(PWD)
GIO_EX_NAME=kitchen

CADDY_EX_PATH=$(PWD)

